const OWNER='jkh2311', REPO='my-site', BRANCH='main';
const cors={'Access-Control-Allow-Origin':'https://haninelife.com','Access-Control-Allow-Headers':'Content-Type, X-Admin-Password','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(o,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{...cors,'content-type':'application/json;charset=utf-8'}});
const ghHeaders=env=>({'Authorization':`Bearer ${env.GITHUB_TOKEN}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'haninelife-admin'});
async function getFile(env,path){const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}?ref=${BRANCH}`,{headers:ghHeaders(env)});if(!r.ok)throw new Error(`GitHub 파일 읽기 실패: ${path}`);const j=await r.json();return {text:decodeURIComponent(escape(atob(j.content.replace(/\n/g,'')))),sha:j.sha}}
async function putFile(env,path,text,message,sha){const body={message,content:btoa(unescape(encodeURIComponent(text))),branch:BRANCH};if(sha)body.sha=sha;const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,{method:'PUT',headers:{...ghHeaders(env),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const t=await r.text();throw new Error(`GitHub 저장 실패: ${path} ${t.slice(0,120)}`)}return r.json()}
async function deleteFile(env,path,sha,message){const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,{method:'DELETE',headers:{...ghHeaders(env),'Content-Type':'application/json'},body:JSON.stringify({message,sha,branch:BRANCH})});if(!r.ok){const t=await r.text();throw new Error(`GitHub 삭제 실패: ${path} ${t.slice(0,120)}`)}return r.json()}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const catName=k=>({admin:'생활·행정',support:'지원·복지',finance:'금융·보험',tips:'생활팁'}[k]||'생활정보');
function cleanSlug(s){return String(s||'').toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
function articleDoc(d,slug){const title=d.title.endsWith('총정리')?d.title:d.title+' 총정리';return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | 한이네생활정보</title><meta name="description" content="${esc(d.description)}"><link rel="canonical" href="https://haninelife.com/articles/${slug}.html"><link rel="stylesheet" href="/style.css?v=59"></head><body><header class="site-header"><div class="container header-inner"><a class="logo" href="/index.html">한이네생활정보</a><nav class="main-nav"><a href="/index.html">홈</a><a href="/articles.html">생활정보</a><a href="/about.html">소개</a><a href="/contact.html">문의</a></nav></div></header><main><article class="section"><div class="container prose"><p class="section-label">${catName(d.category)}</p><h1>${esc(title)}</h1><p>${esc(d.date)} 기준 · 최신 공식 안내 확인</p><div class="admin-managed-body">${d.bodyHtml}</div></div></article></main><footer class="site-footer"><div class="container copyright">© 2026 한이네생활정보. All rights reserved.</div></footer></body></html>`}
const xmlEsc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const cdata=s=>String(s||'').replace(/]]>/g,']]]]><![CDATA[>');
function rssItem(d,slug){const title=d.title.endsWith('총정리')?d.title:d.title+' 총정리';const url=`https://haninelife.com/articles/${slug}.html`;return `    <item data-slug="${slug}">\n      <title>${xmlEsc(title)}</title>\n      <link>${url}</link>\n      <guid isPermaLink="true">${url}</guid>\n      <description><![CDATA[${cdata(d.description)}]]></description>\n      <content:encoded><![CDATA[${cdata(d.bodyHtml)}]]></content:encoded>\n    </item>`}
async function updateRss(env,d,slug){let f;try{f=await getFile(env,'rss.xml')}catch{const base=`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">\n  <channel>\n    <title>한이네생활정보</title>\n    <link>https://haninelife.com/</link>\n    <description>생활에 필요한 다양한 정보를 알기 쉽게 정리해 제공하는 생활정보 사이트입니다.</description>\n    <language>ko-KR</language>\n  </channel>\n</rss>\n`;await putFile(env,'rss.xml',base,'Create RSS feed');f=await getFile(env,'rss.xml')}
const item=rssItem(d,slug);const re=new RegExp(`\\s*<item data-slug="${slug}">[\\s\\S]*?<\\/item>\\s*`);let out=f.text;if(re.test(out))out=out.replace(re,'\n'+item+'\n');else out=out.replace(/\s*<\/channel>/,'\n'+item+'\n  </channel>');if(out!==f.text)await putFile(env,'rss.xml',out,'Update RSS feed',f.sha)}
async function removeFromRss(env,slug){try{const f=await getFile(env,'rss.xml');const re=new RegExp(`\\s*<item data-slug="${slug}">[\\s\\S]*?<\\/item>\\s*`);const out=f.text.replace(re,'\n');if(out!==f.text)await putFile(env,'rss.xml',out,'Remove article from RSS',f.sha)}catch{}}
async function posts(env){const f=await getFile(env,'article-index.json');return JSON.parse(f.text)}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:cors});const u=new URL(req.url);if(req.headers.get('X-Admin-Password')!==env.ADMIN_PASSWORD)return json({error:'관리자 비밀번호가 맞지 않습니다.'},401);try{
if(u.pathname==='/api/posts'&&req.method==='GET'){const a=await posts(env);return json({posts:a.map(x=>({...x,slug:x.url.split('/').pop().replace('.html',''),category:x.category.includes('금융')?'finance':x.category.includes('지원')?'support':x.category.includes('생활팁')?'tips':'admin'}))})}
if(u.pathname==='/api/post'&&req.method==='GET'){const slug=cleanSlug(u.searchParams.get('slug'));const f=await getFile(env,`articles/${slug}.html`);const title=(f.text.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]?.replace(/<[^>]+>/g,'')||slug;const desc=(f.text.match(/<meta name="description" content="([^"]*)"/i)||[])[1]||'';let article=(f.text.match(/<div class="admin-managed-body">([\s\S]*?)<\/div>\s*<\/div>\s*<\/article>/i)||[])[1];if(!article){article=(f.text.match(/<article[^>]*>([\s\S]*?)<\/article>/i)||[])[1]||''}const a=await posts(env);const it=a.find(x=>x.url.endsWith('/'+slug+'.html'))||{};const category=(it.category||'').includes('금융')?'finance':(it.category||'').includes('지원')?'support':(it.category||'').includes('생활팁')?'tips':'admin';return json({slug,title,description:desc,category,articleHtml:article})}
if(u.pathname==='/api/publish'&&req.method==='POST'){const d=await req.json();const slug=cleanSlug(d.mode==='edit'?d.originalSlug:d.slug);if(!slug||!d.title) return json({error:'제목/파일명이 필요합니다.'},400);const path=`articles/${slug}.html`;let existing=null;try{existing=await getFile(env,path)}catch{}
let html;if(d.mode==='edit'&&existing){if(existing.text.includes('admin-managed-body'))html=existing.text.replace(/<div class="admin-managed-body">[\s\S]*?<\/div>\s*<\/div>\s*<\/article>/i,`<div class="admin-managed-body">${d.bodyHtml}</div></div></article>`);else html=existing.text.replace(/<article[^>]*>[\s\S]*?<\/article>/i,`<article class="section"><div class="container prose"><p class="section-label">${catName(d.category)}</p><h1>${esc(d.title)}</h1><p>${esc(d.date)} 기준 · 최신 공식 안내 확인</p><div class="admin-managed-body">${d.bodyHtml}</div></div></article>`);html=html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(d.title)} | 한이네생활정보</title>`).replace(/<meta name="description" content="[^"]*">/i,`<meta name="description" content="${esc(d.description)}">`)}else html=articleDoc(d,slug);
await putFile(env,path,html,`${d.mode==='edit'?'Update':'Publish'} article: ${slug}`,existing?.sha);
const idxF=await getFile(env,'article-index.json');let idx=JSON.parse(idxF.text);const item={title:d.title.endsWith('총정리')?d.title:d.title+' 총정리',description:d.description,category:catName(d.category),url:`/articles/${slug}.html`};const ix=idx.findIndex(x=>x.url===item.url);if(ix>=0)idx[ix]=item;else idx.unshift(item);await putFile(env,'article-index.json',JSON.stringify(idx,null,2),'Update article search index',idxF.sha);
const sm=await getFile(env,'sitemap.xml');const loc=`https://haninelife.com/articles/${slug}.html`;if(!sm.text.includes(`<loc>${loc}</loc>`)){const out=sm.text.replace('</urlset>',`  <url><loc>${loc}</loc></url>\n</urlset>`);await putFile(env,'sitemap.xml',out,'Update sitemap',sm.sha)}
const list=await getFile(env,'articles.html');const card=`<a class="card article-list-card" data-category="${d.category}" href="/articles/${slug}.html"><span class="tag">${catName(d.category)}</span><h2>${esc(item.title)}</h2><p>${esc(d.description)}</p></a>`;let lt=list.text;const re=new RegExp(`<a class="card article-list-card"[^>]*href="/articles/${slug}\\.html"[\\s\\S]*?<\\/a>`);if(re.test(lt))lt=lt.replace(re,card);else lt=lt.replace('<div class="list-grid category-list" id="article-list">','<div class="list-grid category-list" id="article-list">\n'+card);if(lt!==list.text)await putFile(env,'articles.html',lt,'Update article list',list.sha);
await updateRss(env,d,slug);
return json({ok:true,slug,url:`https://haninelife.com/articles/${slug}.html`})}
if(u.pathname==='/api/delete'&&req.method==='POST'){const d=await req.json();const slug=cleanSlug(d.slug);if(!slug)return json({error:'삭제할 파일명이 필요합니다.'},400);const path=`articles/${slug}.html`;const article=await getFile(env,path);await deleteFile(env,path,article.sha,`Delete article: ${slug}`);
const idxF=await getFile(env,'article-index.json');let idx=JSON.parse(idxF.text);idx=idx.filter(x=>x.url!==`/articles/${slug}.html`);await putFile(env,'article-index.json',JSON.stringify(idx,null,2),'Remove article from search index',idxF.sha);
const sm=await getFile(env,'sitemap.xml');const loc=`https://haninelife.com/articles/${slug}.html`;const escaped=loc.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');let smOut=sm.text.replace(new RegExp(`\\s*<url>\\s*<loc>${escaped}<\\/loc>[\\s\\S]*?<\\/url>\\s*`,'g'),'\\n');if(smOut!==sm.text)await putFile(env,'sitemap.xml',smOut,'Remove article from sitemap',sm.sha);
const list=await getFile(env,'articles.html');const re=new RegExp(`\\s*<a class="card article-list-card"[^>]*href="/articles/${slug}\\.html"[\\s\\S]*?<\\/a>\\s*`);const lt=list.text.replace(re,'\\n');if(lt!==list.text)await putFile(env,'articles.html',lt,'Remove article from article list',list.sha);
await removeFromRss(env,slug);
return json({ok:true,slug})}
return json({error:'Not found'},404)}catch(e){return json({error:e.message||String(e)},500)}}};